[service]
host="0.0.0.0"
port=50052

[model.text]
name = "sentence-transformers/clip-ViT-B-32-multilingual-v1"
cache_folder = "models/text"

[model.image]
name = "patrickjohncyh/fashion-clip"
cache_folder = "models"
pretrained_model_folder = "models--patrickjohncyh--fashion-clip"

[test.data]
text_embeddings = "tests/data/text_embeddings.json"
image_embeddings = "tests/data/image_embeddings.json"
text_example = "This is an example sentence."
image = "tests/data/test_image.jpg"
image_url = "https://fns.modanisa.com/r/pro2/2022/12/30/z--8598610-2.jpg"
