replicaCount: 1

namespace:
  create: true

image:
  repository: registry.gitlab.com/modanisatech/sherlock/personalizaiton/embed-rs
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred

nameOverride: "embed-rs"
fullnameOverride: "embed-rs"

ports:
  - name: http
    protocol: TCP
    containerPort: 8888
    servicePort: 80

# serviceMonitoring:
#   enabled: true
#   port: "http"

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: personalization-embed-rs-phoenix.modanisa.net
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: personalization-embed-rs-phoenix.modanisa.net
      servicePort: 80
      paths:
        - /

istio:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

livenessProbe:
  httpGet:
    path: "/health"
    port: http
  initialDelaySeconds: 1
  periodSeconds: 1
  timeoutSeconds: 1
  failureThreshold: 100
  successThreshold: 1


readinessProbe:
  httpGet:
    path: "/health"
    port: http
  initialDelaySeconds: 1
  periodSeconds: 1
  timeoutSeconds: 1
  failureThreshold: 100
  successThreshold: 1

resources:
  # limits:
  #   memory: 256Mi
  requests:
    cpu: 500m
    memory: 2048Mi

# volumes:
#   - name: prod-config
#     secret:
#       secretName: prod-config-secret

# volumeMounts:
#   - mountPath: /app/.config
#     name: prod-config
# sealedSecret:
#   enabled: true

secrets: []

volumes:
  - name: models
    nfs:
      server: 10.200.50.2
      path: ecom_fileshare/nfs/personalization/models

volumeMounts:
  - mountPath: /models
    name: models