name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: install optimum-cli
      run: python -m pip install optimum
    - name: Install dependencies
      run: poetry install
    - name: install just
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.cargo/bin
    - name: Build
      run: just build
    - name: download models
      run: just download-models
    - name: Run tests
      run: just unit-test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Publish to crates.io dry run
      run: |
        cargo login ${{ secrets.CRATES_IO_TOKEN }}
        cargo publish --dry-run

    - name: Cache publish-action bin
      id: cache-publish-action
      uses: actions/cache@v3
      env:
        cache-name: cache-publish-action
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.2.0

    # install publish-action by cargo in github action
    - name: Install publish-action
      if: steps.cache-publish-action.outputs.cache-hit != 'true'
      run:
        cargo install publish-action --version=0.2.0
    
    - name: Run publish-action
      id: publish-action
      run:
        publish-action
      env:
        GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    - name: Update Changelog.md
      if: steps.publish-action.outputs.new_version == 'true' && steps.publish-action.outputs.publish == 'true'
      run: |
        changelog -o Changelog.md
